# Generated by Django 5.1.4 on 2024-12-23 16:58

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='date_joined',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2024, 12, 23, 16, 58, 52, 806864, tzinfo=datetime.timezone.utc)),
        ),
    ]
