# Generated by Django 5.1.4 on 2024-12-27 12:23

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_shopuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='date_joined',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2024, 12, 27, 12, 23, 22, 124377, tzinfo=datetime.timezone.utc)),
        ),
    ]
