# Generated by Django 5.1.4 on 2024-12-29 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_shopuser_date_joined'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='shopuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shopuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
    ]
