# Generated by Django 5.1.4 on 2025-01-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_shopuser_options_remove_shopuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='address',
            field=models.TextField(),
        ),
    ]
