# Generated by Django 5.1.4 on 2025-05-06 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.MaxLengthValidator(11, message='Phone number must have 11 digits')]),
        ),
    ]
