# Generated by Django 5.1.4 on 2025-05-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_shopuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
