# Generated by Django 5.1.4 on 2024-12-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت پس از تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='offers',
            field=models.PositiveIntegerField(default=0, verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(default=0, verbose_name='وزن'),
        ),
    ]
