# Generated by Django 5.1.4 on 2024-12-29 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارشات'},
        ),
    ]
