# Generated by Django 5.1.4 on 2025-01-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار پرداخت'), ('PROCESSING', 'در حال پردازش'), ('SHIPPED', 'ارسال شده'), ('DELIVERED', 'تحویل داده شده'), ('CANCELLED', 'لغو شده')], default='PENDING', max_length=50),
        ),
    ]
