# Generated by Django 5.1.4 on 2025-01-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار پرداخت'), ('PROCESSING', 'در حال پردازش'), ('SHIPPED', 'ارسال شده'), ('DELIVERED', 'تحویل داده شده'), ('CANCELLED', 'لغو شده'), ('RETURNED', 'مرجوع شده')], default='PENDING', max_length=50),
        ),
    ]
