# Generated by Django 5.1.4 on 2025-01-14 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orderaddress_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_reason', models.TextField(default='Please explain your reason...')),
                ('image', models.ImageField(upload_to='returned_products')),
                ('delivery_date', models.DateTimeField()),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('UNDER REVIEW', 'UNDER REVIEW'), ('CONFIRMATION', 'CONFIRMATION'), ('REJECTED', 'REJECTED'), ('COMPLETED', 'COMPLETED'), ('REFUNDED', 'REFUNDED')], default='UNDER REVIEW', max_length=50)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-request_date'],
                'indexes': [models.Index(fields=['-request_date'], name='orders_retu_request_308be2_idx')],
            },
        ),
    ]
