# Generated by Django 5.1.4 on 2025-01-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_returnedproducts_additional_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnedproducts',
            name='delivery_date',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
